services:
    app:
        ports:
            - 9013:80
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
            UPLOAD_LIMIT: 64M

    db:
        ports:
            - 23313:3306

    redis:
        ports:
            - 26393:6379

####> symfony/mailer ###
#  mailer:
#    image: axllent/mailpit
#    ports:
#      - "1025"
#      - "8025"
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1
####< symfony/mailer ###
#
####> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
####< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
#  mercure:
#    ports:
#      - "80"
###< symfony/mercure-bundle ###
